name: Release

on:

  release:

    types:

      - created




jobs:




  publish_on_linux:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2       

    - uses: actions/setup-node@master

      with:

        node-version: 14

        registry-url: https://npm.pkg.github.com/

        scope: "@agulseren19"

    - name: install dependencies

      working-directory: ./AslihanGulseren/gmailApp

      run: npm install

    - name: publish

      env:

        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      working-directory: ./AslihanGulseren/gmailApp

      run: npm run publish




  publish_on_mac:

    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-node@master

      with:

        node-version: 14

        registry-url: https://npm.pkg.github.com/

        scope: "@agulseren19"

    - name: install dependencies

      working-directory: ./AslihanGulseren/gmailApp

      run: npm install

    - name: publish

      env:

        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      working-directory: ./AslihanGulseren/gmailApp

      run: npm run publish




  publish_on_win:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2       

    - uses: actions/setup-node@master

      with:

        node-version: 14

        registry-url: https://npm.pkg.github.com/

        scope: "@agulseren19"

    - name: install dependencies

      working-directory: ./AslihanGulseren/gmailApp

      run: npm install

    - name: publish

      env:

        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      working-directory: ./AslihanGulseren/gmailApp

      run: npm run publish
